name: 🐛 Bug Report
description:  "Report a reproducible bug in the project"
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Reminder:** Everything you enter here will be publicly visible.
        Do not include any kind of sensitive data!
        
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Clear and concise description of the bug
      placeholder: What went wrong?
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step guide to reproduce the bug
      placeholder: |
        1. Go to...
        2. Run...
        3. See error
    validations:
      required: false

  - type: input
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser and package version
      placeholder: e.g. Edge 1.0, dv.manager 2.0, dv.explorer.parameter 1.0
