name: ✨ Feature Request
description: Suggest a new feature or improvement for the project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **Reminder:** Everything you enter here will be publicly visible.
        Do not include any kind of sensitive data!
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem are you trying to solve? Why is it important?
      placeholder: It’s frustrating when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: I’d like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives or Workarounds
      description: Have you tried other solutions? Why do they fall short?
      placeholder: Other ways I tried...
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any extra details, screenshots, or examples?
      placeholder: Add any context or screenshots about the feature here.
    validations:
      required: false
